AWSTemplateFormatVersion: 2010-09-09
Description: Configure a role in target accounts granting access for the Terraform pipeline

Parameters:
  AdministratorAccountId:
    Type: String
    Description: AWS Account Id of the account from which to grant access
    MaxLength: 12
    MinLength: 12

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: TerraformExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AdministratorAccountId}:user/terraform
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess
