AWSTemplateFormatVersion: 2010-09-09
Description: Creates Terraform state infrastructure in the target account. (DynamoDB table and S3 bucket)

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: terraform-lock-states
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub terraform-state-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
